export type State = {
  name: string;
  abbreviation: string;
  country: string;
};
export const states: State[] = [
  { name: "Alabama", abbreviation: "AL", country: "US" },
  { name: "Alaska", abbreviation: "AK", country: "US" },
  { name: "Arizona", abbreviation: "AZ", country: "US" },
  { name: "Arkansas", abbreviation: "AR", country: "US" },
  { name: "California", abbreviation: "CA", country: "US" },
  { name: "Colorado", abbreviation: "CO", country: "US" },
  { name: "Connecticut", abbreviation: "CT", country: "US" },
  { name: "Delaware", abbreviation: "DE", country: "US" },
  { name: "Florida", abbreviation: "FL", country: "US" },
  { name: "Georgia", abbreviation: "GA", country: "US" },
  { name: "Hawaii", abbreviation: "HI", country: "US" },
  { name: "Idaho", abbreviation: "ID", country: "US" },
  { name: "Illinois", abbreviation: "IL", country: "US" },
  { name: "Indiana", abbreviation: "IN", country: "US" },
  { name: "Iowa", abbreviation: "IA", country: "US" },
  { name: "Kansas", abbreviation: "KS", country: "US" },
  { name: "Kentucky", abbreviation: "KY", country: "US" },
  { name: "Louisiana", abbreviation: "LA", country: "US" },
  { name: "Maine", abbreviation: "ME", country: "US" },
  { name: "Maryland", abbreviation: "MD", country: "US" },
  { name: "Massachusetts", abbreviation: "MA", country: "US" },
  { name: "Michigan", abbreviation: "MI", country: "US" },
  { name: "Minnesota", abbreviation: "MN", country: "US" },
  { name: "Mississippi", abbreviation: "MS", country: "US" },
  { name: "Missouri", abbreviation: "MO", country: "US" },
  { name: "Montana", abbreviation: "MT", country: "US" },
  { name: "Nebraska", abbreviation: "NE", country: "US" },
  { name: "Nevada", abbreviation: "NV", country: "US" },
  { name: "New Hampshire", abbreviation: "NH", country: "US" },
  { name: "New Jersey", abbreviation: "NJ", country: "US" },
  { name: "New Mexico", abbreviation: "NM", country: "US" },
  { name: "New York", abbreviation: "NY", country: "US" },
  { name: "North Carolina", abbreviation: "NC", country: "US" },
  { name: "North Dakota", abbreviation: "ND", country: "US" },
  { name: "Ohio", abbreviation: "OH", country: "US" },
  { name: "Oklahoma", abbreviation: "OK", country: "US" },
  { name: "Oregon", abbreviation: "OR", country: "US" },
  { name: "Pennsylvania", abbreviation: "PA", country: "US" },
  { name: "Rhode Island", abbreviation: "RI", country: "US" },
  { name: "South Carolina", abbreviation: "SC", country: "US" },
  { name: "South Dakota", abbreviation: "SD", country: "US" },
  { name: "Tennessee", abbreviation: "TN", country: "US" },
  { name: "Texas", abbreviation: "TX", country: "US" },
  { name: "Utah", abbreviation: "UT", country: "US" },
  { name: "Vermont", abbreviation: "VT", country: "US" },
  { name: "Virginia", abbreviation: "VA", country: "US" },
  { name: "Washington", abbreviation: "WA", country: "US" },
  { name: "West Virginia", abbreviation: "WV", country: "US" },
  { name: "Wisconsin", abbreviation: "WI", country: "US" },
  { name: "Wyoming", abbreviation: "WY", country: "US" },
  { name: "Manitoba", abbreviation: "MB", country: "Canada" },
  { name: "Alberta", abbreviation: "AB", country: "Canada" },
  { name: "British Columbia", abbreviation: "BC", country: "Canada" },
  { name: "New Brunswick", abbreviation: "NB", country: "Canada" },
  { name: "Newfoundland and Labrador", abbreviation: "NL", country: "Canada" },
  { name: "Northwest Territories", abbreviation: "NT", country: "Canada" },
  { name: "Nova Scotia", abbreviation: "NS", country: "Canada" },
  { name: "Nunavut", abbreviation: "NU", country: "Canada" },
  { name: "Ontario", abbreviation: "ON", country: "Canada" },
  { name: "Prince Edward Island", abbreviation: "PE", country: "Canada" },
  { name: "Quebec", abbreviation: "QC", country: "Canada" },
  { name: "Saskatchewan", abbreviation: "SK", country: "Canada" },
  { name: "Yukon", abbreviation: "YT", country: "Canada" },
];
