create table "public"."cardListings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "listing_uuid" uuid not null default gen_random_uuid(),
    "card_uuid" uuid not null default gen_random_uuid(),
    "street" text not null,
    "city" text not null,
    "stateId" smallint not null,
    "zipcode" text not null,
    "propertyType" text not null,
    "price" real not null,
    "parking" smallint,
    "bedrooms" smallint,
    "bathrooms" smallint,
    "squareFootage" bigint,
    "lotSize" bigint,
    "yearBuilt" integer not null,
    "countryId" smallint not null,
    "description" text,
    "is_deleted" boolean default false
);


alter table "public"."cardListings" enable row level security;

create table "public"."listingImages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "images_uuid" uuid default gen_random_uuid(),
    "image_name" character varying not null,
    "listing_uuid" uuid not null default gen_random_uuid()
);


alter table "public"."listingImages" enable row level security;

CREATE UNIQUE INDEX "cardListings_listing_uuid_key" ON public."cardListings" USING btree (listing_uuid);

CREATE UNIQUE INDEX "cardListings_pkey" ON public."cardListings" USING btree (id);

CREATE UNIQUE INDEX "listingImages_pkey" ON public."listingImages" USING btree (id);

alter table "public"."cardListings" add constraint "cardListings_pkey" PRIMARY KEY using index "cardListings_pkey";

alter table "public"."listingImages" add constraint "listingImages_pkey" PRIMARY KEY using index "listingImages_pkey";

alter table "public"."cardListings" add constraint "cardListings_listing_uuid_key" UNIQUE using index "cardListings_listing_uuid_key";

alter table "public"."cardListings" add constraint "public_cardListings_card_uuid_fkey" FOREIGN KEY (card_uuid) REFERENCES cards("cardId") not valid;

alter table "public"."cardListings" validate constraint "public_cardListings_card_uuid_fkey";

alter table "public"."listingImages" add constraint "public_listingImages_listing_uuid_fkey" FOREIGN KEY (listing_uuid) REFERENCES "cardListings"(listing_uuid) not valid;

alter table "public"."listingImages" validate constraint "public_listingImages_listing_uuid_fkey";

grant delete on table "public"."cardListings" to "anon";

grant insert on table "public"."cardListings" to "anon";

grant references on table "public"."cardListings" to "anon";

grant select on table "public"."cardListings" to "anon";

grant trigger on table "public"."cardListings" to "anon";

grant truncate on table "public"."cardListings" to "anon";

grant update on table "public"."cardListings" to "anon";

grant delete on table "public"."cardListings" to "authenticated";

grant insert on table "public"."cardListings" to "authenticated";

grant references on table "public"."cardListings" to "authenticated";

grant select on table "public"."cardListings" to "authenticated";

grant trigger on table "public"."cardListings" to "authenticated";

grant truncate on table "public"."cardListings" to "authenticated";

grant update on table "public"."cardListings" to "authenticated";

grant delete on table "public"."cardListings" to "service_role";

grant insert on table "public"."cardListings" to "service_role";

grant references on table "public"."cardListings" to "service_role";

grant select on table "public"."cardListings" to "service_role";

grant trigger on table "public"."cardListings" to "service_role";

grant truncate on table "public"."cardListings" to "service_role";

grant update on table "public"."cardListings" to "service_role";

grant delete on table "public"."listingImages" to "anon";

grant insert on table "public"."listingImages" to "anon";

grant references on table "public"."listingImages" to "anon";

grant select on table "public"."listingImages" to "anon";

grant trigger on table "public"."listingImages" to "anon";

grant truncate on table "public"."listingImages" to "anon";

grant update on table "public"."listingImages" to "anon";

grant delete on table "public"."listingImages" to "authenticated";

grant insert on table "public"."listingImages" to "authenticated";

grant references on table "public"."listingImages" to "authenticated";

grant select on table "public"."listingImages" to "authenticated";

grant trigger on table "public"."listingImages" to "authenticated";

grant truncate on table "public"."listingImages" to "authenticated";

grant update on table "public"."listingImages" to "authenticated";

grant delete on table "public"."listingImages" to "service_role";

grant insert on table "public"."listingImages" to "service_role";

grant references on table "public"."listingImages" to "service_role";

grant select on table "public"."listingImages" to "service_role";

grant trigger on table "public"."listingImages" to "service_role";

grant truncate on table "public"."listingImages" to "service_role";

grant update on table "public"."listingImages" to "service_role";


